[project]
name = "portfolio-advisor"
version = "0.1.0"
description = "Portfolio selection and advisory application"
authors = [
    { name = "zolcsika71", email = "bushdoctor2008@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = ["pandas (>=3.0.5,<4.0.0)", "python-calamine (>=0.8.2,<0.9.0)", "pyyaml (>=6.0.2,<7.0.0)", "requests (==2.34.2)", "xlrd (==2.0.2)"]

[tool.poetry]
packages = [
    { include = "portfolio_advisor", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
pandas = ">=3.0.5,<4.0.0"
python-calamine = ">=0.8.2,<0.9.0"
pyyaml = ">=6.0.2,<7.0.0"
xlrd = "==2.0.2"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "ruff (>=0.16.1,<0.17.0)",
    "mypy (>=2.3.0,<3.0.0)",
    "types-pyyaml (>=6.0.12.20250915,<7.0.0.0)",
    "pandas-stubs (>=3.0.5.260730,<4.0.0.0)"
]
